sudo: false
language: node_js
cache:
  directories:
  - node_modules
  - bower_components
notifications:
  email: false
  slack:
    rooms:
      secure: iu7Lfy20XWeN4x2TNIFA+ozQQq2Uewi9txnQKOvoyWsx7gM1YP2xVZSh6ZAiZpAXCjvsOYpeM/2c7j5FeVc1PONjJMrXJ2bwdKSNmFV5hGxJ8cb92Sjl6t3/W6826+MDQWaJvwwqtV/dJBjHwZ4UjEkrauFGiGZCnJRIet3bH4I=
node_js:
  - '4'
  - iojs-v3
  - iojs-v2
  - iojs-v1
  - '0.12'
  - '0.10'
before_install:
  - npm i -g npm@^2.0.0
install:
  - ./node_modules/bower/bin/bower install -f
before_script:
  - npm prune
script:
- ./node_modules/postcss/bin/postcss -c postcss.json
- cp src/index.html dist/index.html
- cp src/img/logo.png dist/assets/logo.png
- cp src/img/favicon.ico dist/assets/favicon.ico
after_success:
  - npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
addons:
  code_climate:
    repo_token: 65bf022d3b618cd3dc544e1996da2a7c98ea425d16b716d7e72adce9f0607c41
