language: node_js
node_js:
  - "0.10"
install: grunt build
deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "www.proux.de"
  skip_cleanup: true
  region: eu-west-1
  local-dir: public
  on:
    branch: master