language: node_js
deploy:
  - provider: s3
    access_key_id: AKIAJC2ZSP5C77YTKKNQ
    secret_access_key:
      secure: XuG/5sMWQzhGn0TMfiF3SGmPkrh9HAk/DziLAGxYzcfNdoJC4rSeqnbzZPxnECnu0XxzvzHlI4UvCi+10qQKvFjECejm6r0idTDfayZ7y6762MmHMsGcZuH2o01yb+pIeKzmfiB0hEPUgV6ApOpKIraLIIMjHaqwbit377h9RB0=
    bucket: www.proux.de
    region: eu-west-1
    endpoint: www.proux.de.s3-website-eu-west-1.amazonaws.com
    skip_cleanup: true
    local-dir: public
    acl: public_read
    on:
      repo: proux/www.proux.de
      branch: master
